package com.swiftlydeveloped.feedbackkit

import com.swiftlydeveloped.feedbackkit.models.Comment
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlinx.serialization.json.boolean
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertTrue
import org.junit.Assert.fail
import org.junit.Test

/**
 * `QA-UNIT04-COMMENTS` `-12` — the Kotlin SDK decodes the payload the server actually
 * sends.
 *
 * The corpus in `src/test/resources/comment-wire-corpus.json` is **not** written here. It
 * is generated by the server's `CommentWireContractTests` from the server's own
 * `CommentResponseDTO` through the server's own configured encoder, and that suite
 * byte-diffs this committed copy against a fresh regeneration.
 *
 * ✅ **GREEN SINCE 2026-08-15** — these cases were authored red on arrival against two
 * shipped defects, and `QA-UNIT10-SDK-PARITY` landed the routed fixes that flipped them:
 *
 *  - `Comment.feedbackId` was a non-nullable `String` with no default, and the server's
 *    comment payload carries no `feedback_id`, so `kotlinx.serialization` raised
 *    `MissingFieldException` on **every** comment list. Now nullable with a null default.
 *  - `Comment.isOfficial` read `is_official`, which the server never sends; it now reads
 *    the server's actual key, `is_admin`.
 *
 * The `fail(...)` guards in the decode cases below are kept: if either defect regresses,
 * they name it instead of surfacing a bare serialization stack trace.
 */
class CommentModelTest {

    /** Replicates `FeedbackKitHttpClient`'s `Json` configuration. */
    private val json = Json {
        ignoreUnknownKeys = true
        isLenient = true
        encodeDefaults = true
        coerceInputValues = true
    }

    private fun corpusText(): String {
        val stream = javaClass.getResourceAsStream("/comment-wire-corpus.json")
        assertNotNull(
            "comment-wire-corpus.json is missing from src/test/resources; regenerate it " +
                "from the server's CommentWireContractTests.",
            stream
        )
        return stream!!.bufferedReader().use { it.readText() }
    }

    /**
     * Green. Establishes that the fixture on disk really is the server's five-key shape and
     * really can express an admin flag, so a red below is the Kotlin model's fault and not
     * a broken or absent fixture.
     */
    @Test
    fun `the corpus fixture is the server's five-key comment shape`() {
        val array = json.parseToJsonElement(corpusText()) as JsonArray
        assertEquals(2, array.size)

        val first = array[0].jsonObject
        assertEquals(
            setOf("id", "content", "user_id", "is_admin", "created_at"),
            first.keys
        )
        // Load-bearing: one entry is admin-flagged and one is not.
        assertTrue(first["is_admin"]!!.jsonPrimitive.boolean)
        assertTrue(!array[1].jsonObject["is_admin"]!!.jsonPrimitive.boolean)

        // The server sends neither of the two keys this SDK's model requires.
        assertTrue("feedback_id" !in first.keys)
        assertTrue("is_official" !in first.keys)
    }

    /**
     * ⚠️ RED ON ARRIVAL — `MissingFieldException` on `feedback_id`.
     *
     * The alternative discovery path for this is a customer reporting that the comment list
     * on Android is empty.
     */
    @Test
    fun `the server comment payload decodes into a list of Comment`() {
        val comments = try {
            json.decodeFromString<List<Comment>>(corpusText())
        } catch (error: Exception) {
            fail(
                "The Kotlin SDK cannot decode the comment payload the server sends: " +
                    "${error::class.simpleName}: ${error.message}. " +
                    "Comment.feedbackId is a non-nullable String with no default and the " +
                    "server sends no feedback_id. Fix models/Comment.kt (QA-UNIT04-COMMENTS -12)."
            )
            return
        }

        assertEquals(2, comments.size)
        assertEquals("11111111-1111-4111-8111-111111111111", comments[0].id)
        assertEquals("Thanks for the report - this ships in 2.4.", comments[0].content)
        assertEquals("fixture-admin-user", comments[0].userId)
        assertEquals("2023-11-14T22:13:20Z", comments[0].createdAt)

        assertEquals("22222222-2222-4222-8222-222222222222", comments[1].id)
        assertEquals("Please add dark mode.", comments[1].content)
        assertEquals("fixture-end-user", comments[1].userId)
        assertEquals("2023-11-14T23:13:20Z", comments[1].createdAt)
    }

    /**
     * ⚠️ RED ON ARRIVAL — the admin flag never arrives.
     *
     * Stated separately from the decode case above because it is a **second, independent**
     * defect: fixing `feedbackId` alone would turn the previous case green and leave this
     * one red, with admin replies rendering as ordinary user comments on Android.
     */
    @Test
    fun `an admin-flagged comment decodes as official`() {
        val comments = try {
            json.decodeFromString<List<Comment>>(corpusText())
        } catch (error: Exception) {
            fail(
                "Blocked by the decode defect above (${error::class.simpleName}). " +
                    "The admin-flag defect is independent: Comment.isOfficial reads " +
                    "is_official and the server sends is_admin, so this case stays red " +
                    "after feedbackId is fixed (QA-UNIT04-COMMENTS -12)."
            )
            return
        }

        assertTrue(
            "The admin-flagged corpus entry decoded as non-official: Comment reads " +
                "is_official, the server sends is_admin.",
            comments[0].isOfficial
        )
        assertTrue(!comments[1].isOfficial)
    }
}
