package com.swiftlydeveloped.feedbackkit

import com.swiftlydeveloped.feedbackkit.models.Feedback
import com.swiftlydeveloped.feedbackkit.models.FeedbackCategory
import com.swiftlydeveloped.feedbackkit.models.FeedbackStatus
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.jsonObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * `QA-UNIT05-FEEDBACK`, Kotlin lane — `-05`, `-10`, `-11`, `-12`.
 *
 * `FeedbackStatusTest` already asserts `displayName`, `jsonValue`, `fromJsonValue`'s round
 * trip and `canVote` **once per status individually**, which is `-01`, `-04` and `-09` in
 * this lane. This file adds the three claims that file cannot make:
 *
 *  - **`-10`, the 7th-status tripwire** — computed over `entries`, so it fires on an
 *    *addition*. A table of six correct pairs stays green when a seventh case appears, and
 *    Kotlin's predicate is a **negation** (`this != COMPLETED && this != REJECTED`, finding
 *    **F1**), so a seventh status would silently become **votable**. Kotlin's `when` would
 *    have given exhaustiveness for free; the remediation is a product change and is out of
 *    scope here.
 *  - **`-11`, cross-client agreement** — the partition expressed in the one vocabulary four
 *    languages share, the wire tokens, so the Swift-side derivation has something to compare
 *    against.
 *  - **`-12`, the server wire corpus** — the payload the server actually sends, decoded by
 *    the SDK's own `Feedback`.
 *
 * The corpus in `src/test/resources/feedback-wire-corpus.json` is **not** written here. It is
 * generated by the server's `FeedbackWireContractTests` from the server's own
 * `FeedbackResponseDTO` through the server's own configured encoder, and that suite
 * byte-diffs this committed copy against a fresh regeneration.
 */
class FeedbackStatusPartitionTest {

    /** Replicates `FeedbackKitHttpClient`'s `Json` configuration. */
    private val json = Json { ignoreUnknownKeys = true }

    private fun corpus(): JsonArray {
        val stream = javaClass.classLoader!!.getResourceAsStream("feedback-wire-corpus.json")
        assertNotNull("feedback-wire-corpus.json is missing from test resources", stream)
        return json.parseToJsonElement(stream!!.bufferedReader().readText()) as JsonArray
    }

    // MARK: -10 · the 7th-status tripwire

    @Test
    fun `there are exactly six statuses and four categories`() {
        // A per-case table cannot detect an ADDITION — a seventh case is simply not in it.
        // `testflight` was itself added after the first clients shipped, so this is the shape
        // of the change this domain actually takes.
        assertEquals(6, FeedbackStatus.entries.size)
        assertEquals(4, FeedbackCategory.entries.size)
    }

    @Test
    fun `the computed can-vote false-set is exactly completed and rejected`() {
        val blocked = FeedbackStatus.entries.filter { !it.canVote }.toSet()
        val votable = FeedbackStatus.entries.filter { it.canVote }.toSet()

        assertEquals(setOf(FeedbackStatus.COMPLETED, FeedbackStatus.REJECTED), blocked)
        assertEquals(
            setOf(
                FeedbackStatus.PENDING,
                FeedbackStatus.APPROVED,
                FeedbackStatus.IN_PROGRESS,
                FeedbackStatus.TESTFLIGHT
            ),
            votable
        )
        assertEquals(FeedbackStatus.entries.size, blocked.size + votable.size)
    }

    @Test
    fun `the six wire tokens are pairwise distinct`() {
        // Derived from `entries` rather than from a table, so it also covers a future case
        // that copy-pastes an existing token — which makes `fromJsonValue` unreachable for
        // one of them with no compiler complaint.
        assertEquals(
            FeedbackStatus.entries.size,
            FeedbackStatus.entries.map { it.jsonValue }.toSet().size
        )
        assertEquals(
            FeedbackStatus.entries.size,
            FeedbackStatus.entries.map { it.displayName }.toSet().size
        )
    }

    // MARK: -11 · cross-client agreement

    @Test
    fun `the Kotlin partition equals the canon every other client must produce`() {
        // The canon written as wire tokens, the only vocabulary Swift, Dart, Kotlin and
        // TypeScript share. The Swift SDK's FeedbackCanVoteParityTests derives all six
        // declarations from source and compares them; this is the runtime half on this side.
        val blockedTokens =
            FeedbackStatus.entries.filter { !it.canVote }.map { it.jsonValue }.toSet()
        assertEquals(setOf("completed", "rejected"), blockedTokens)
    }

    // MARK: -05 · the unknown-token disposition

    @Test
    fun `an unknown token returns null from fromJsonValue`() {
        // Kotlin's disposition is the null one — neither a throw (Swift) nor a sentinel
        // coercion (Flutter, finding F6). It is the input to QA-UNIT10-SDK-PARITY's tolerant
        // element-drop decision: a wrapper catching a decode error would never fire here.
        assertNull(FeedbackStatus.fromJsonValue("quantum"))
        assertNull(FeedbackStatus.fromJsonValue(""))
        assertNull(FeedbackStatus.fromJsonValue("in-progress"))
    }

    @Test
    fun `a known token still parses, including the case-insensitive alias`() {
        // The paired positive: without it, the null cases above are satisfied by a parser
        // that returns null for everything.
        assertEquals(FeedbackStatus.IN_PROGRESS, FeedbackStatus.fromJsonValue("in_progress"))
        assertEquals(FeedbackStatus.IN_PROGRESS, FeedbackStatus.fromJsonValue("IN_PROGRESS"))
        assertEquals(FeedbackStatus.IN_PROGRESS, FeedbackStatus.fromJsonValue("inprogress"))
        assertEquals(FeedbackStatus.REJECTED, FeedbackStatus.fromJsonValue("rejected"))
    }

    @Test
    fun `the serializer throws on an unknown token, unlike fromJsonValue`() {
        // Two dispositions in one SDK, and they differ. `@Serializable` throws; the companion
        // returns null. Nothing in the tree reconciles them, so both are recorded.
        var threw = false
        try {
            json.decodeFromString(FeedbackStatus.serializer(), "\"quantum\"")
        } catch (expected: Exception) {
            threw = true
        }
        assertTrue("The @Serializable decoder no longer throws on an unknown status", threw)

        // Paired positive.
        assertEquals(
            FeedbackStatus.TESTFLIGHT,
            json.decodeFromString(FeedbackStatus.serializer(), "\"testflight\"")
        )
    }

    // MARK: -12 · the server wire corpus

    @Test
    fun `the corpus fixture is the server shape and can express a failure`() {
        // Non-vacuity for the decode cases below: an emptied fixture, or one whose sparse
        // entry had quietly gained the optional keys, would leave them meaningless.
        val entries = corpus()
        assertEquals(3, entries.size)
        assertEquals(41, entries[0].jsonObject.keys.size)
        assertTrue(entries[0].jsonObject.containsKey("sync_states"))
        assertFalse(entries[2].jsonObject.containsKey("user_email"))
        assertFalse(entries[2].jsonObject.containsKey("sync_states"))
    }

    @Test
    fun `Feedback decodes every field it declares from the server corpus`() {
        val entries = corpus()
        val item = json.decodeFromJsonElement(Feedback.serializer(), entries[0])

        assertEquals("11111111-1111-4111-8111-111111111111", item.id)
        assertEquals("Add a dark theme", item.title)
        assertEquals("The list is hard to read at night.", item.description)
        assertEquals(FeedbackStatus.IN_PROGRESS, item.status)
        assertEquals(FeedbackCategory.FEATURE_REQUEST, item.category)
        assertEquals(7, item.voteCount)
        assertTrue(item.hasVoted)
        assertEquals(3, item.commentCount)
        assertEquals("2023-11-14T22:13:20Z", item.createdAt)
        assertEquals("2023-11-14T23:13:20Z", item.updatedAt)
        assertEquals("fixture-end-user", item.userId)
        assertEquals(true, item.isHiddenOverLimit)
    }

    @Test
    fun `all three corpus entries decode, exercising three arms of each enum`() {
        val items = corpus().map { json.decodeFromJsonElement(Feedback.serializer(), it) }

        assertEquals(
            listOf(FeedbackStatus.IN_PROGRESS, FeedbackStatus.TESTFLIGHT, FeedbackStatus.REJECTED),
            items.map { it.status }
        )
        assertEquals(
            listOf(
                FeedbackCategory.FEATURE_REQUEST,
                FeedbackCategory.BUG_REPORT,
                FeedbackCategory.OTHER
            ),
            items.map { it.category }
        )
        // The sparse entry's optionals are absent and its required core is present.
        assertNull(items[2].isHiddenOverLimit?.takeIf { it })
        assertEquals("Crash on launch", items[2].title)
        assertEquals(0, items[2].voteCount)
    }

    @Test
    fun `the submitter email reaches the Kotlin model through @SerialName user_email`() {
        // ⚠️ FLIPPED 2026-08-15 by QA-UNIT10-SDK-PARITY. This case previously RECORDED the
        // shipped defect: `Feedback.email` carried no @SerialName, so it read the wire key
        // `email` — which the server never sends — and was silently null on every payload.
        // The fix (@SerialName("user_email") on models/Feedback.kt) landed with this flip,
        // and the case now asserts the address the corpus entry actually carries.
        val entries = corpus()
        val populated = json.decodeFromJsonElement(Feedback.serializer(), entries[0])

        // The server really did send an address on this entry…
        assertTrue(entries[0].jsonObject.containsKey("user_email"))
        // …and the model now sees it.
        assertEquals("fixture-user@example.invalid", populated.email)

        // Paired negative: the sparse entry has no user_email, and the field stays null
        // rather than picking a value up from some other key.
        val sparse = json.decodeFromJsonElement(Feedback.serializer(), entries[2])
        assertNull(sparse.email)
    }
}
