package com.swiftlydeveloped.feedbackkit

import androidx.compose.ui.graphics.Color
import com.swiftlydeveloped.feedbackkit.errors.FeedbackKitError
import com.swiftlydeveloped.feedbackkit.models.CreateFeedbackRequest
import com.swiftlydeveloped.feedbackkit.models.Feedback
import com.swiftlydeveloped.feedbackkit.models.FeedbackCategory
import com.swiftlydeveloped.feedbackkit.models.FeedbackStatus
import com.swiftlydeveloped.feedbackkit.models.RegisterUserRequest
import com.swiftlydeveloped.feedbackkit.models.SdkUser
import com.swiftlydeveloped.feedbackkit.models.TrackEventResponse
import com.swiftlydeveloped.feedbackkit.models.VoteResponse
import com.swiftlydeveloped.feedbackkit.theme.FeedbackKitTheme
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerializationException
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.decodeFromJsonElement
import kotlinx.serialization.json.double
import kotlinx.serialization.json.encodeToJsonElement
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Assert.fail
import org.junit.Test

/**
 * `QA-UNIT10-SDK-PARITY`, Kotlin lane — `-07`, `-17`, `-18`, `-20`, `-21`, `-22`.
 *
 * Every decode fixture here is a committed corpus file generated by the server's wire
 * contract suites through the server's own configured encoder — none is hand-written in
 * this file. Where a case needs a malformed variant, it mutates a **parsed** corpus row at
 * runtime (list surgery on the `JsonArray`), which is the established practice from
 * `FeedbackStatusPartitionTest` / `CommentModelTest`.
 *
 * Several cases below are marked **⚠️ RECORDED AS SHIPPED**: they assert a shipped defect
 * verbatim, green, so the defect is pinned and named. Fixing the product must flip the
 * corresponding case deliberately — these tests do NOT author the desired behaviour.
 */
class SdkParityTest {

    /** Replicates `FeedbackKitHttpClient`'s `Json` configuration, like `CommentModelTest`. */
    private val json = Json {
        ignoreUnknownKeys = true
        isLenient = true
        encodeDefaults = true
        coerceInputValues = true
    }

    /**
     * A probe type for the `-07` "why coercion cannot save it" case: same enum, but the
     * property carries a **default**, which is the one thing `Feedback.status` lacks.
     */
    @Serializable
    private data class StatusWithDefaultProbe(
        val status: FeedbackStatus = FeedbackStatus.PENDING
    )

    private fun corpusArray(name: String): JsonArray {
        val stream = javaClass.classLoader!!.getResourceAsStream(name)
        assertNotNull("$name is missing from test resources", stream)
        return json.parseToJsonElement(stream!!.bufferedReader().readText()) as JsonArray
    }

    private fun requestCanon(): JsonObject {
        val stream = javaClass.classLoader!!.getResourceAsStream("request-wire-corpus.json")
        assertNotNull("request-wire-corpus.json is missing from test resources", stream)
        return json.parseToJsonElement(stream!!.bufferedReader().readText()) as JsonObject
    }

    // MARK: -07 · list tolerance

    /**
     * ⚠️ RECORDED AS SHIPPED — one unknown status token poisons the whole list.
     *
     * The tolerance corpus is four feedback rows, one of which (`quantum_launch`, index 2)
     * carries a status token this SDK has never heard of — the exact shape of a server that
     * shipped a new status before the client updated. Decoding the array as
     * `List<Feedback>` THROWS, so the customer consequence is an **empty feedback list on
     * every Android install** the moment the server adds a status, not a list missing one
     * row. A tolerant per-element decode would have to be product code; fixing it must flip
     * this test deliberately.
     */
    @Test
    fun `one unknown status token poisons the whole four-row list decode`() {
        val rows = corpusArray("feedback-tolerance-corpus.json")

        // Non-vacuity: the poison row really is there, really is unknown to this SDK.
        assertEquals(4, rows.size)
        val poisonToken = rows[2].jsonObject["status"]!!.jsonPrimitive.content
        assertEquals("quantum_launch", poisonToken)
        assertNull(FeedbackStatus.fromJsonValue(poisonToken))

        var threw = false
        try {
            json.decodeFromJsonElement<List<Feedback>>(rows)
        } catch (expected: SerializationException) {
            threw = true
        }
        assertTrue(
            "List<Feedback> decode of the tolerance corpus no longer throws — either the " +
                "product grew tolerance (flip this case deliberately) or the corpus lost " +
                "its unknown-status row.",
            threw
        )
    }

    /**
     * ⚠️ RECORDED AS SHIPPED — why the configured `coerceInputValues = true` cannot save it.
     *
     * `coerceInputValues` replaces an unknown enum token with the property's **default**.
     * `Feedback.status` is a non-nullable `FeedbackStatus` with **no default**, so there is
     * nothing to coerce to and the decode throws. The probe type below is identical except
     * for the default, and the very same poison row coerces cleanly — pinning that the
     * missing default, not the Json configuration, is what makes the list decode fatal.
     */
    @Test
    fun `coerceInputValues cannot rescue status because Feedback declares no default`() {
        val poisonRow = corpusArray("feedback-tolerance-corpus.json")[2]

        // The poison row alone throws as Feedback (no default to coerce to)…
        var threw = false
        try {
            json.decodeFromJsonElement<Feedback>(poisonRow)
        } catch (expected: SerializationException) {
            threw = true
        }
        assertTrue("The single unknown-status row now decodes as Feedback", threw)

        // …and the same unknown token coerces the moment a default exists, proving the
        // configured mechanism works and only Feedback's declaration blocks it.
        val probe = json.decodeFromJsonElement<StatusWithDefaultProbe>(poisonRow.jsonObject.let {
            JsonObject(mapOf("status" to it["status"]!!))
        })
        assertEquals(FeedbackStatus.PENDING, probe.status)
    }

    /**
     * The paired positive for `-07`: with the poison row surgically removed at runtime, the
     * remaining three rows decode in order — including the last row, which carries an
     * unknown extra key (`unknown_future_key`) that `ignoreUnknownKeys = true` tolerates.
     * So the SDK's tolerance boundary is exactly: unknown KEYS fine, unknown enum TOKENS
     * fatal.
     */
    @Test
    fun `removing the unknown-status row decodes the surviving three, unknown keys tolerated`() {
        val rows = corpusArray("feedback-tolerance-corpus.json")
        // Non-vacuity for the unknown-key half: the surviving last row really carries one.
        assertTrue(rows[3].jsonObject.containsKey("unknown_future_key"))

        val survivors = JsonArray(rows.filterIndexed { index, _ -> index != 2 })
        val items = json.decodeFromJsonElement<List<Feedback>>(survivors)

        assertEquals(3, items.size)
        assertEquals(
            listOf("Tolerance row one", "Tolerance row two", "Tolerance row four"),
            items.map { it.title }
        )
        assertEquals(
            listOf(FeedbackStatus.PENDING, FeedbackStatus.TESTFLIGHT, FeedbackStatus.COMPLETED),
            items.map { it.status }
        )
        assertEquals(
            listOf(
                FeedbackCategory.FEATURE_REQUEST,
                FeedbackCategory.BUG_REPORT,
                FeedbackCategory.OTHER
            ),
            items.map { it.category }
        )
    }

    // MARK: -21 · required-field census

    /**
     * ⚠️ RECORDED AS SHIPPED — finding **F2**, the headline: every vote and unvote on
     * Android throws today.
     *
     * `VoteResponse.success` is required and default-less, and the server has NEVER sent a
     * `success` key on the vote payload — the corpus shows the wire shape is exactly
     * `{feedback_id, vote_count, has_voted}`. So the HTTP call succeeds, the vote is
     * recorded server-side, and the SDK then throws `MissingFieldException` decoding the
     * 2xx body: the user's vote "fails" on screen while having actually landed. Fixing
     * `VoteResponse` must flip this case deliberately.
     */
    @Test
    fun `every vote response decode throws MissingFieldException on success`() {
        val row = corpusArray("vote-wire-corpus.json")[0]

        // Non-vacuity: the server's row carries exactly the three keys, no "success",
        // and demonstrably expresses a real vote state.
        assertEquals(setOf("feedback_id", "vote_count", "has_voted"), row.jsonObject.keys)
        assertTrue(row.jsonObject["has_voted"]!!.jsonPrimitive.content.toBoolean())
        assertEquals("8", row.jsonObject["vote_count"]!!.jsonPrimitive.content)

        try {
            json.decodeFromJsonElement<VoteResponse>(row)
            fail(
                "VoteResponse decoded the server's vote payload — the shipped defect " +
                    "(required, default-less `success`) is gone; flip this RECORDED case " +
                    "into the fixed-behaviour assertion deliberately."
            )
        } catch (error: SerializationException) {
            assertEquals("MissingFieldException", error::class.simpleName)
            assertTrue(
                "The decode failure no longer names `success`: ${error.message}",
                error.message.orEmpty().contains("success")
            )
        }
    }

    /**
     * ⚠️ RECORDED AS SHIPPED — F2's twin: every tracked event on Android throws today.
     *
     * `TrackEventResponse.success` is required and default-less; the event payload the
     * server actually sends is `{id, event_name, user_id, properties?, created_at}` with no
     * `success` key. Same customer shape as the vote arm: the event IS recorded, the SDK
     * call throws anyway.
     */
    @Test
    fun `every track-event response decode throws MissingFieldException on success`() {
        val row = corpusArray("event-wire-corpus.json")[0]

        // Non-vacuity: a real event row, no "success" anywhere.
        assertEquals("feedback_list", row.jsonObject["event_name"]!!.jsonPrimitive.content)
        assertFalse(row.jsonObject.containsKey("success"))

        try {
            json.decodeFromJsonElement<TrackEventResponse>(row)
            fail(
                "TrackEventResponse decoded the server's event payload — the shipped " +
                    "defect (required, default-less `success`) is gone; flip this " +
                    "RECORDED case deliberately."
            )
        } catch (error: SerializationException) {
            assertEquals("MissingFieldException", error::class.simpleName)
            assertTrue(
                "The decode failure no longer names `success`: ${error.message}",
                error.message.orEmpty().contains("success")
            )
        }
    }

    /**
     * ⚠️ RECORDED AS SHIPPED — finding **F3**: `SdkUser` is a model of phantoms.
     *
     * The server's SDK-user payload is `{id, user_id, mrr, first_seen_at, last_seen_at}`.
     * Of the six properties the Kotlin model declares, only `id` binds; `email`, `name`,
     * `externalId`, `metadata` and `createdAt` read keys the server never sends and are
     * null on every payload, while the keys the server DOES send (`user_id`, `mrr`,
     * `first_seen_at`, `last_seen_at`) have no property reading them and vanish under
     * `ignoreUnknownKeys`. The decode "succeeds" — into an object that knows nothing.
     */
    @Test
    fun `SdkUser binds only id, every other declared property is a phantom`() {
        val row = corpusArray("sdk-user-wire-corpus.json")[0]

        // Non-vacuity through the raw JsonObject: the wire row demonstrably carries the
        // data the model then loses.
        assertEquals("fixture-end-user", row.jsonObject["user_id"]!!.jsonPrimitive.content)
        assertEquals(42.5, row.jsonObject["mrr"]!!.jsonPrimitive.double, 0.0)
        assertTrue(row.jsonObject.containsKey("first_seen_at"))
        assertTrue(row.jsonObject.containsKey("last_seen_at"))

        val user = json.decodeFromJsonElement<SdkUser>(row)
        assertEquals("99999999-9999-4999-8999-999999999999", user.id)
        assertNull(user.email)
        assertNull(user.name)
        assertNull(user.externalId)
        assertNull(user.metadata)
        assertNull(user.createdAt)
    }

    // MARK: -22 · encode direction

    /**
     * ⚠️ RECORDED AS SHIPPED — the mailing-list opt-in silently never leaves the phone.
     *
     * `CreateFeedbackRequest.subscribeToMailingList` / `mailingListEmailTypes` carry no
     * `@SerialName`, so the client emits camelCase keys the server does not read; and the
     * client emits `email` where the server's canon key is `user_email`. The server ignores
     * unknown body keys, so the feedback IS created — minus the submitter's email and
     * minus their mailing-list subscription, with no error anywhere. The canon below is
     * loaded from `request-wire-corpus.json` (`create_feedback`), generated server-side.
     */
    @Test
    fun `CreateFeedbackRequest emits keys the server canon does not read`() {
        val canonKeys = requestCanon()["create_feedback"]!!.jsonObject.keys

        // Non-vacuity: the canon really is the server's seven-key shape.
        assertEquals(
            setOf(
                "title", "description", "category", "user_id", "user_email",
                "subscribe_to_mailing_list", "mailing_list_email_types"
            ),
            canonKeys
        )

        val emitted = json.encodeToJsonElement(
            CreateFeedbackRequest(
                title = "Add a dark theme",
                description = "The list is hard to read at night.",
                category = FeedbackCategory.FEATURE_REQUEST,
                email = "fixture-user@example.invalid",
                userId = "fixture-end-user",
                subscribeToMailingList = true,
                mailingListEmailTypes = listOf("status_change")
            )
        ).jsonObject.keys

        // The shipped emission, verbatim: camelCase mailing-list keys and bare `email`.
        assertTrue("subscribeToMailingList" in emitted)
        assertTrue("mailingListEmailTypes" in emitted)
        assertTrue("email" in emitted)

        // The intersection failure, explicitly: none of those three is in the server's
        // key set, so all three are silently dropped on arrival…
        assertFalse("subscribeToMailingList" in canonKeys)
        assertFalse("mailingListEmailTypes" in canonKeys)
        assertFalse("email" in canonKeys)
        // …and the keys the server WOULD read never get emitted.
        assertFalse("subscribe_to_mailing_list" in emitted)
        assertFalse("mailing_list_email_types" in emitted)
        assertFalse("user_email" in emitted)
    }

    /**
     * ⚠️ RECORDED AS SHIPPED — F3's encode half: `RegisterUserRequest` and the server's
     * `register_sdk_user` canon (`{user_id, mrr}`) share **zero** keys. The model emits
     * `{email, name, external_id, metadata}`; the server reads none of them and receives
     * neither a user id nor an MRR from this SDK.
     */
    @Test
    fun `RegisterUserRequest shares zero keys with the register_sdk_user canon`() {
        val canonKeys = requestCanon()["register_sdk_user"]!!.jsonObject.keys
        assertEquals(setOf("user_id", "mrr"), canonKeys)

        val emitted = json.encodeToJsonElement(
            RegisterUserRequest(
                email = "fixture-user@example.invalid",
                name = "Fixture User",
                externalId = "fixture-external",
                metadata = mapOf("plan" to "pro")
            )
        ).jsonObject.keys

        assertEquals(setOf("email", "name", "external_id", "metadata"), emitted)
        assertEquals(emptySet<String>(), emitted intersect canonKeys)
    }

    // MARK: -18 · environment enumeration, -17 · config validation

    /**
     * `-18` — the full environment-to-host map as a single equality over `entries`, so an
     * added member (or a changed host) reddens this case rather than slipping past a
     * per-member table. `FeedbackKitConfigTest` asserts the four URLs individually; this is
     * the addition tripwire it cannot be.
     */
    @Test
    fun `the environment enumeration is exactly the four known hosts`() {
        assertEquals(
            mapOf(
                "PRODUCTION" to "https://api.prod.getfeedbackkit.com",
                "STAGING" to "https://api.testflight.getfeedbackkit.com",
                "LOCAL" to "http://10.0.2.2:8080",
                "LOCAL_DEVICE" to "http://localhost:8080"
            ),
            Environment.entries.associate { it.name to it.baseUrl }
        )
    }

    /**
     * `-17` ⚠️ RECORDED AS SHIPPED — an empty API key is accepted silently.
     *
     * `FeedbackKitConfig(apiKey = "")` neither throws nor warns; the empty string is stored
     * and every subsequent request goes out with an empty `X-API-Key` header, surfacing
     * only as a 401 at first network contact instead of at the construction site where the
     * mistake was made. The remaining defaults (`timeout = 30_000L`, `debug = false`) are
     * already pinned by `FeedbackKitConfigTest.default config uses production environment`
     * and are not re-asserted here.
     */
    @Test
    fun `an empty api key is accepted silently`() {
        val config = FeedbackKitConfig(apiKey = "")
        assertEquals("", config.apiKey)
    }

    // MARK: -20 · theme

    /**
     * `-20` ⚠️ RECORDED — the two "shared-palette" SDKs disagree on light mode.
     *
     * Kotlin's shipped light theme is pinned verbatim below: white background,
     * `0xFFF9FAFB` card, `0xFF1F2937` text. Flutter ships the same palette with background
     * and card **swapped** (`0xFFF9FAFB` background, white card) and text `0xFF111827` —
     * so the same app on the two platforms renders light mode with inverted surfaces.
     * Which side is canonical is a product decision; this pins Kotlin's half so the
     * eventual reconciliation flips a named test rather than drifting silently.
     */
    @Test
    fun `the shipped light theme values are pinned verbatim`() {
        val light = FeedbackKitTheme.Light
        assertEquals(Color(0xFFFFFFFF), light.backgroundColor)
        assertEquals(Color(0xFFF9FAFB), light.cardBackgroundColor)
        assertEquals(Color(0xFF1F2937), light.textColor)
    }

    /**
     * Both presets exist, and dark's surface stack is pinned so a palette edit on either
     * side of the light/dark pair reddens a named case.
     */
    @Test
    fun `the dark preset exists and its surface stack is pinned`() {
        assertNotNull(FeedbackKitTheme.Light)
        assertNotNull(FeedbackKitTheme.Dark)

        val dark = FeedbackKitTheme.Dark
        assertEquals(Color(0xFF60A5FA), dark.primaryColor)
        assertEquals(Color(0xFF111827), dark.backgroundColor)
        assertEquals(Color(0xFF1F2937), dark.cardBackgroundColor)
        assertEquals(Color(0xFF374151), dark.borderColor)
    }

    /**
     * ⚠️ RECORDED AS SHIPPED (`-12`'s information-loss arm) — 422 and 429 fall into
     * `UnknownError`, whose `statusCode` is hard-coded **`null`**
     * (`FeedbackKitError.kt:84-87`): Kotlin is the ONLY SDK of six that discards the
     * actual status on the unknown-4xx path. Swift/Vapor carry `.serverError(422)`, JS and
     * Flutter carry the code on the base error. An integrator branching on `statusCode`
     * cannot tell a 422 from a 429 — or from a genuinely unknown failure — on Android.
     * `FeedbackKitErrorTest` pins the class mapping; this pins the loss.
     */
    @Test
    fun `the unknown-4xx fallback discards the status code entirely`() {
        val validation = FeedbackKitError.fromStatusCode(422, "Validation failed")
        val rateLimited = FeedbackKitError.fromStatusCode(429, "Too many requests")

        assertTrue(validation is FeedbackKitError.UnknownError)
        assertTrue(rateLimited is FeedbackKitError.UnknownError)
        assertNull("422 must currently be discarded — see RECORDED note", validation.statusCode)
        assertNull("429 must currently be discarded — see RECORDED note", rateLimited.statusCode)
        assertEquals("UNKNOWN", validation.code)
    }

    /**
     * ⚠️ RECORDED AS SHIPPED — `merge` discards its receiver entirely.
     *
     * `FeedbackKitTheme.merge(other)` is documented as "Merge this theme with another" and
     * is implemented as `= other`: every receiver-side customization is thrown away, so a
     * partial override object replaces the whole theme with defaults instead of layering.
     * A real merge would need per-field defaulting; until that lands, this pins the
     * shipped identity so a fix flips a named test.
     */
    @Test
    fun `merge returns the other theme verbatim, discarding the receiver`() {
        val customized = FeedbackKitTheme.Dark
        val override = FeedbackKitTheme(primaryColor = Color(0xFFEF4444))

        val merged = customized.merge(override)

        assertEquals(override, merged)
        // The receiver's dark background is gone — replaced by `override`'s default white.
        assertEquals(Color(0xFFFFFFFF), merged.backgroundColor)
    }
}
